import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

import { Button } from '@/components/ui/button'
import { supabase } from '@/lib/supabase'
import { ChatMessage } from '@/components/ChatMessage'

export function Chats() {
  const navigate = useNavigate()
  const [isLoading, setIsLoading] = useState(true)
  const [messages, setMessages] = useState<any[]>([])
  const [inputValue, setInputValue] = useState('')

  useEffect(() => {
    // Check if user is authenticated
    const checkAuth = async () => {
      const { data: { session } } = await supabase.auth.getSession()
      
      if (!session) {
        navigate('/login')
        return
      }
      
      setIsLoading(false)
      // Here you would load chat threads from the backend
    }

    checkAuth()
  }, [navigate])

  const handleLogout = async () => {
    await supabase.auth.signOut()
    navigate('/login')
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!inputValue.trim()) return

    // Add user message
    const newUserMessage = {
      id: Date.now(),
      role: 'user',
      content: inputValue,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, newUserMessage])
    setInputValue('')

    // Simulate assistant response (in a real app, this would call the backend)
    setTimeout(() => {
      const newAssistantMessage = {
        id: Date.now() + 1,
        role: 'assistant',
        content: `This is a simulated response to your message: "${inputValue}". In a real implementation, this would be generated by the AI assistant using the document retrieval system.`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, newAssistantMessage])
    }, 1000)
  }

  if (isLoading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        Loading...
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <header className="border-b bg-white">
        <div className="container flex h-16 items-center justify-between px-4">
          <h1 className="text-xl font-semibold">Document Copilot</h1>
          <Button onClick={handleLogout} variant="outline">
            Logout
          </Button>
        </div>
      </header>
      
      <main className="container flex-grow py-8 flex flex-col">
        <div className="mb-6 flex items-center justify-between">
          <h2 className="text-2xl font-bold">Your Chats</h2>
          <Button>New Chat</Button>
        </div>
        
        {/* Chat messages area */}
        <div className="flex-grow bg-white rounded-lg border shadow-sm mb-6 p-4 overflow-y-auto max-h-[500px]">
          {messages.length === 0 ? (
            <div className="text-center py-8 text-gray-500">
              Start a conversation by sending a message below
            </div>
          ) : (
            <div className="space-y-4">
              {messages.map((message) => (
                <ChatMessage
                  key={message.id}
                  role={message.role}
                  content={message.content}
                  timestamp={message.timestamp}
                />
              ))}
            </div>
          )}
        </div>
        
        {/* Message input */}
        <form onSubmit={handleSubmit} className="flex gap-2">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            placeholder="Type your message..."
            className="flex-grow border rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
          <Button type="submit">Send</Button>
        </form>
      </main>
    </div>
  )
}